version: '3.8'

services:
  # Frontend
  streamlit:
    container_name: streamlit
    build:
      context: ./frontend
      # context: streamlit
    restart: always
    ports:
      - "30006:8090"
    environment:
      azure_cv_key: ${azure_cv_key}
      azure_cv_endpoint: ${azure_cv_endpoint}
      atlas_nomic_key: ${atlas_nomic_key}
